//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncludeTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IncludeTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; This file is used to generate Prelude.h, which sets up the initial environment for the preprocessor.
        ///
        ///; Standard macros
        ///__STDC__
        ///__STDC_VERSION__
        ///__STDC_HOSTED__
        ///__cplusplus
        ///__TIMESTAMP__
        ///
        ///; Microsoft defines, taken from https://msdn.microsoft.com/en-us/library/b0084kay.aspx
        ///_ATL_VER
        ///__AVX__
        ///__AVX2__
        ///_CHAR_UNSIGNED
        ///__CLR_VER
        ///__cplusplus_cli
        ///__cplusplus_winrt
        ///_CPPRTTI
        ///_CPPUNWIND
        ///_DEBUG
        ///_DLL
        ///_INTEGRAL_MAX_BITS
        ///_M_AMD64
        ///_M_ARM
        ///_M_CEE
        ///_M_CEE_PURE
        ///_M_CEE_SAFE
        ///_M_IX86
        ///_M_ARM_FP
        ///_M_I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prelude {
            get {
                return ResourceManager.GetString("Prelude", resourceCulture);
            }
        }
    }
}
