// Copyright 1998-2017 Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"

#define BEGIN_SLATE_FUNCTION_BUILD_OPTIMIZATION BEGIN_FUNCTION_BUILD_OPTIMIZATION
#define END_SLATE_FUNCTION_BUILD_OPTIMIZATION   END_FUNCTION_BUILD_OPTIMIZATION
