// Copyright 1998-2017 Epic Games, Inc. All Rights Reserved.

/*=============================================================================
	VulkanCommon.usf: Common Vulkan shader code
=============================================================================*/

// Update this GUID to improve shader recompilation for Vulkan only shaders
// GUID = {792BDC0A-A4A8-402F-8752-3F9F642A03C0}
// Glslang 1.0.49.0

#pragma once
