//-----------------------------------------------------------------------------
// File:		LPVClearLists.usf
//
// Summary:		Shader to clear LPV linked lists
//
// Created:		2013-12-08
//
// Author:		mailto:benwood@microsoft.com
//
//				Copyright (C) Microsoft. All rights reserved.
//-----------------------------------------------------------------------------

/*------------------------------------------------------------------------------
	Compile time parameters:
------------------------------------------------------------------------------*/

#include "Common.ush"
#include "LPVWriteCommon.ush" 
#include "LPVGeometryVolumeCommon.ush"

//------------------------------------------------------------------------------

RWByteAddressBuffer								RWVplListHeadBuffer;
RWByteAddressBuffer								RWGvListHeadBuffer;

//------------------------------------------------------------------------------
[numthreads(4,4,4)]
void CSClearLists(uint3 DTid : SV_DispatchThreadID) 
{
	uint i = GetGridAddress( DTid );

	// 0 - terminated lists (index+1) - prevents infinite loop when reading off the end of the list
	RWVplListHeadBuffer.Store( i*4, 0 ); 
	RWGvListHeadBuffer.Store( i*4, 0 );
}

//------------------------------------------------------------------------------
