// Copyright 1998-2017 Epic Games, Inc. All Rights Reserved.

// PS4 directory may not exists. As a result a shader compiler may not be able to
// find file for include scanning, but the include scanner will silently ignore
// PS4 directory by design.
//
// TODO(VR team): move shader file and C++ into a plugin.

#include "Common.ush"
#include "PostProcessCommon.ush"
#include "PS4/PostProcessHMDMorpheus.usf"
